//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMT.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IdentityText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IdentityText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PMT.Common.Resources.IdentityText", typeof(IdentityText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a phone number.
        /// </summary>
        public static string AddAPhoneNumber {
            get {
                return ResourceManager.GetString("AddAPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred..
        /// </summary>
        public static string AnErrorHasOccurred {
            get {
                return ResourceManager.GetString("AnErrorHasOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association Form.
        /// </summary>
        public static string AssociationForm {
            get {
                return ResourceManager.GetString("AssociationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve successfully authenticated with.
        /// </summary>
        public static string AssociationFormMessage1 {
            get {
                return ResourceManager.GetString("AssociationFormMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a user name for this site below and click the Register button to finish
        ///                logging in..
        /// </summary>
        public static string AssociationFormMessage2 {
            get {
                return ResourceManager.GetString("AssociationFormMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password Form.
        /// </summary>
        public static string ChangePasswordForm {
            get {
                return ResourceManager.GetString("ChangePasswordForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your account settings.
        /// </summary>
        public static string ChangeYourAccountSettings {
            get {
                return ResourceManager.GetString("ChangeYourAccountSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your password.
        /// </summary>
        public static string ChangeYourPassword {
            get {
                return ResourceManager.GetString("ChangeYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click here to log in.
        /// </summary>
        public static string ClickHereToLogIn {
            get {
                return ResourceManager.GetString("ClickHereToLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfirmEmail.
        /// </summary>
        public static string ConfirmEmail {
            get {
                return ResourceManager.GetString("ConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account.
        /// </summary>
        public static string CreateANewAccount {
            get {
                return ResourceManager.GetString("CreateANewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Local Login.
        /// </summary>
        public static string CreateLocalLogin {
            get {
                return ResourceManager.GetString("CreateLocalLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Password.
        /// </summary>
        public static string CreatePassword {
            get {
                return ResourceManager.GetString("CreatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Link.
        /// </summary>
        public static string EmailLink {
            get {
                return ResourceManager.GetString("EmailLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter verification code.
        /// </summary>
        public static string EnterVerificationCode {
            get {
                return ResourceManager.GetString("EnterVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your emai.
        /// </summary>
        public static string EnterYourEmai {
            get {
                return ResourceManager.GetString("EnterYourEmai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Logins.
        /// </summary>
        public static string ExternalLogins {
            get {
                return ResourceManager.GetString("ExternalLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to verify phone.
        /// </summary>
        public static string FailedToVerifyPhone {
            get {
                return ResourceManager.GetString("FailedToVerifyPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password Confirmation.
        /// </summary>
        public static string ForgotPasswordConfirmation {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string ForgotYourPassword {
            get {
                return ResourceManager.GetString("ForgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid code..
        /// </summary>
        public static string InvalidCode {
            get {
                return ResourceManager.GetString("InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt..
        /// </summary>
        public static string InvalidLoginAttempt {
            get {
                return ResourceManager.GetString("InvalidLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failure.
        /// </summary>
        public static string LoginFailure {
            get {
                return ResourceManager.GetString("LoginFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login from your account.
        /// </summary>
        public static string LoginFromYourAccount {
            get {
                return ResourceManager.GetString("LoginFromYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in using your.
        /// </summary>
        public static string LogInUsingYour {
            get {
                return ResourceManager.GetString("LogInUsingYour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no external authentication services configured. See.
        /// </summary>
        public static string ManageLogingsMessage1 {
            get {
                return ResourceManager.GetString("ManageLogingsMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for details on setting up this ASP.NET application to support logging in via external services..
        /// </summary>
        public static string ManageLogingsMessage2 {
            get {
                return ResourceManager.GetString("ManageLogingsMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this article.
        /// </summary>
        public static string ManageLogingsMessage3 {
            get {
                return ResourceManager.GetString("ManageLogingsMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your external logins.
        /// </summary>
        public static string ManageYourExternalLogins {
            get {
                return ResourceManager.GetString("ManageYourExternalLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email to reset your password.
        /// </summary>
        public static string PleaseCheckYourEmailToResetYourPassword {
            get {
                return ResourceManager.GetString("PleaseCheckYourEmailToResetYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a new user.
        /// </summary>
        public static string RegisterAsANewUser {
            get {
                return ResourceManager.GetString("RegisterAsANewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this.
        /// </summary>
        public static string RemoveThis {
            get {
                return ResourceManager.GetString("RemoveThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password confirmation.
        /// </summary>
        public static string ResetPasswordConfirmation {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your password.
        /// </summary>
        public static string ResetYourPassword {
            get {
                return ResourceManager.GetString("ResetYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Two-Factor Authentication Provider.
        /// </summary>
        public static string SelectTwoFactorAuthenticationProvider {
            get {
                return ResourceManager.GetString("SelectTwoFactorAuthenticationProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send verification code.
        /// </summary>
        public static string SendVerificationCode {
            get {
                return ResourceManager.GetString("SendVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set password.
        /// </summary>
        public static string SetPassword {
            get {
                return ResourceManager.GetString("SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have a local username/password for this site. Add a local.
        /// </summary>
        public static string SetPasswordMessage1 {
            get {
                return ResourceManager.GetString("SetPasswordMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account so you can log in without an external login..
        /// </summary>
        public static string SetPasswordMessage2 {
            get {
                return ResourceManager.GetString("SetPasswordMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for confirming your email. Please.
        /// </summary>
        public static string ThankYouForConfirmingYourEmailPlease {
            get {
                return ResourceManager.GetString("ThankYouForConfirmingYourEmailPlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The external login was removed..
        /// </summary>
        public static string TheExternalLoginWasRemoved {
            get {
                return ResourceManager.GetString("TheExternalLoginWasRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no external authentication services configured.
        /// </summary>
        public static string ThereAreNoExternalAuthenticationServicesConfigured {
            get {
                return ResourceManager.GetString("ThereAreNoExternalAuthenticationServicesConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuccessful login with service.
        /// </summary>
        public static string UnsuccessfulLoginWithService {
            get {
                return ResourceManager.GetString("UnsuccessfulLoginWithService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a local account to log in.
        /// </summary>
        public static string UseALocalAccountToLogIn {
            get {
                return ResourceManager.GetString("UseALocalAccountToLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string Verify {
            get {
                return ResourceManager.GetString("Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Phone Number.
        /// </summary>
        public static string VerifyPhoneNumber {
            get {
                return ResourceManager.GetString("VerifyPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed..
        /// </summary>
        public static string YourPasswordHasBeenChanged {
            get {
                return ResourceManager.GetString("YourPasswordHasBeenChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset. Please.
        /// </summary>
        public static string YourPasswordHasBeenResetPlease {
            get {
                return ResourceManager.GetString("YourPasswordHasBeenResetPlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been set..
        /// </summary>
        public static string YourPasswordHasBeenSet {
            get {
                return ResourceManager.GetString("YourPasswordHasBeenSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your phone number was added..
        /// </summary>
        public static string YourPhoneNumberWasAdded {
            get {
                return ResourceManager.GetString("YourPhoneNumberWasAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your phone number was removed..
        /// </summary>
        public static string YourPhoneNumberWasRemoved {
            get {
                return ResourceManager.GetString("YourPhoneNumberWasRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your security code is:.
        /// </summary>
        public static string YourSecurityCodeIs {
            get {
                return ResourceManager.GetString("YourSecurityCodeIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your two-factor authentication provider has been set..
        /// </summary>
        public static string YourTwoFactorAuthenticationProviderHasBeenSet {
            get {
                return ResourceManager.GetString("YourTwoFactorAuthenticationProviderHasBeenSet", resourceCulture);
            }
        }
    }
}
