//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMT.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessagesText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PMT.Common.Resources.MessagesText", typeof(MessagesText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account couldn&apos;t be modified.
        /// </summary>
        public static string AccountCouldntBeModified {
            get {
                return ResourceManager.GetString("AccountCouldntBeModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account has been modified.
        /// </summary>
        public static string AccountHasBeenModified {
            get {
                return ResourceManager.GetString("AccountHasBeenModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account successfully deleted.
        /// </summary>
        public static string AccountSuccessfullyDeleted {
            get {
                return ResourceManager.GetString("AccountSuccessfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this category and all its subcategories?.
        /// </summary>
        public static string CategoryDeleteWarningLine {
            get {
                return ResourceManager.GetString("CategoryDeleteWarningLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category has been modified.
        /// </summary>
        public static string CategoryHasBeenModified {
            get {
                return ResourceManager.GetString("CategoryHasBeenModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this account?.
        /// </summary>
        public static string MoneyAccountsDeleteWarningLine1 {
            get {
                return ResourceManager.GetString("MoneyAccountsDeleteWarningLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning, all transactions of the account will be removed..
        /// </summary>
        public static string MoneyAccountsDeleteWarningLine2 {
            get {
                return ResourceManager.GetString("MoneyAccountsDeleteWarningLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New account couldn&apos;t be created.
        /// </summary>
        public static string NewAccountCouldntBeCreated {
            get {
                return ResourceManager.GetString("NewAccountCouldntBeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New account has been created.
        /// </summary>
        public static string NewAccountHasBeenCreated {
            get {
                return ResourceManager.GetString("NewAccountHasBeenCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New category couldn&apos;t be created.
        /// </summary>
        public static string NewCategoryCouldntBeCreated {
            get {
                return ResourceManager.GetString("NewCategoryCouldntBeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New category has been created.
        /// </summary>
        public static string NewCategoryHasBeenCreated {
            get {
                return ResourceManager.GetString("NewCategoryHasBeenCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New subcategory couldn&apos;t be created.
        /// </summary>
        public static string NewSubcategoryCouldntBeCreated {
            get {
                return ResourceManager.GetString("NewSubcategoryCouldntBeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New subcategory has been created.
        /// </summary>
        public static string NewSubcategoryHasBeenCreated {
            get {
                return ResourceManager.GetString("NewSubcategoryHasBeenCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New transaction couldn&apos;t be created.
        /// </summary>
        public static string NewTransactionCouldntBeCreated {
            get {
                return ResourceManager.GetString("NewTransactionCouldntBeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New transaction has been created.
        /// </summary>
        public static string NewTransactionHasBeenCreated {
            get {
                return ResourceManager.GetString("NewTransactionHasBeenCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings couldn&apos;t be updated.
        /// </summary>
        public static string SettingsCouldntBeUpdated {
            get {
                return ResourceManager.GetString("SettingsCouldntBeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings updated.
        /// </summary>
        public static string SettingsUpdated {
            get {
                return ResourceManager.GetString("SettingsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcategory couldn&apos;t be modified.
        /// </summary>
        public static string SubcategoryCouldntBeModified {
            get {
                return ResourceManager.GetString("SubcategoryCouldntBeModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this subcategory?.
        /// </summary>
        public static string SubCategoryDeleteWarningLine {
            get {
                return ResourceManager.GetString("SubCategoryDeleteWarningLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted.
        /// </summary>
        public static string SuccessfullyDeleted {
            get {
                return ResourceManager.GetString("SuccessfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction couldn&apos;t be modified.
        /// </summary>
        public static string TransactionCouldntBeModified {
            get {
                return ResourceManager.GetString("TransactionCouldntBeModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this transaction?.
        /// </summary>
        public static string TransactionDeleteWarningLine {
            get {
                return ResourceManager.GetString("TransactionDeleteWarningLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction has been modified.
        /// </summary>
        public static string TransactionHasBeenModified {
            get {
                return ResourceManager.GetString("TransactionHasBeenModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction successfully deleted.
        /// </summary>
        public static string TransactionSuccessfullyDeleted {
            get {
                return ResourceManager.GetString("TransactionSuccessfullyDeleted", resourceCulture);
            }
        }
    }
}
