//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMT.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SeedingDataText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SeedingDataText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PMT.Common.Resources.SeedingDataText", typeof(SeedingDataText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment.
        /// </summary>
        public static string Adjustment {
            get {
                return ResourceManager.GetString("Adjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowance.
        /// </summary>
        public static string Allowance {
            get {
                return ResourceManager.GetString("Allowance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appliances.
        /// </summary>
        public static string Appliances {
            get {
                return ResourceManager.GetString("Appliances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Babysitter.
        /// </summary>
        public static string Babysitter {
            get {
                return ResourceManager.GetString("Babysitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baby Supplies.
        /// </summary>
        public static string BabySupplies {
            get {
                return ResourceManager.GetString("BabySupplies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus.
        /// </summary>
        public static string Bonus {
            get {
                return ResourceManager.GetString("Bonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        public static string Books {
            get {
                return ResourceManager.GetString("Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrow.
        /// </summary>
        public static string Borrow {
            get {
                return ResourceManager.GetString("Borrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Insurance.
        /// </summary>
        public static string CarInsurance {
            get {
                return ResourceManager.GetString("CarInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Maintenance.
        /// </summary>
        public static string CarMaintenance {
            get {
                return ResourceManager.GetString("CarMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinic.
        /// </summary>
        public static string Clinic {
            get {
                return ResourceManager.GetString("Clinic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clothing.
        /// </summary>
        public static string Clothing {
            get {
                return ResourceManager.GetString("Clothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coffe/Bar.
        /// </summary>
        public static string CoffeBar {
            get {
                return ResourceManager.GetString("CoffeBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collecting debts.
        /// </summary>
        public static string Collectindebts {
            get {
                return ResourceManager.GetString("Collectindebts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cosmetics.
        /// </summary>
        public static string Cosmetics {
            get {
                return ResourceManager.GetString("Cosmetics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses.
        /// </summary>
        public static string Courses {
            get {
                return ResourceManager.GetString("Courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daycare.
        /// </summary>
        public static string Daycare {
            get {
                return ResourceManager.GetString("Daycare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dentist.
        /// </summary>
        public static string Dentist {
            get {
                return ResourceManager.GetString("Dentist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor.
        /// </summary>
        public static string Doctor {
            get {
                return ResourceManager.GetString("Doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electricity.
        /// </summary>
        public static string Electricity {
            get {
                return ResourceManager.GetString("Electricity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food.
        /// </summary>
        public static string Food {
            get {
                return ResourceManager.GetString("Food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel.
        /// </summary>
        public static string Fuel {
            get {
                return ResourceManager.GetString("Fuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Furniture.
        /// </summary>
        public static string Furniture {
            get {
                return ResourceManager.GetString("Furniture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gambling.
        /// </summary>
        public static string Gambling {
            get {
                return ResourceManager.GetString("Gambling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas.
        /// </summary>
        public static string Gas {
            get {
                return ResourceManager.GetString("Gas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift.
        /// </summary>
        public static string Gift {
            get {
                return ResourceManager.GetString("Gift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gifts.
        /// </summary>
        public static string Gifts {
            get {
                return ResourceManager.GetString("Gifts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glasses.
        /// </summary>
        public static string Glasses {
            get {
                return ResourceManager.GetString("Glasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groceries.
        /// </summary>
        public static string Groceries {
            get {
                return ResourceManager.GetString("Groceries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grooming.
        /// </summary>
        public static string Grooming {
            get {
                return ResourceManager.GetString("Grooming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gym.
        /// </summary>
        public static string Gym {
            get {
                return ResourceManager.GetString("Gym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health.
        /// </summary>
        public static string Health {
            get {
                return ResourceManager.GetString("Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hobbies.
        /// </summary>
        public static string Hobbies {
            get {
                return ResourceManager.GetString("Hobbies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Insurance.
        /// </summary>
        public static string HomeInsurance {
            get {
                return ResourceManager.GetString("HomeInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Maintenance.
        /// </summary>
        public static string HomeMaintenance {
            get {
                return ResourceManager.GetString("HomeMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Phone.
        /// </summary>
        public static string HomePhone {
            get {
                return ResourceManager.GetString("HomePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Services.
        /// </summary>
        public static string HomeServices {
            get {
                return ResourceManager.GetString("HomeServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest.
        /// </summary>
        public static string Interest {
            get {
                return ResourceManager.GetString("Interest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet.
        /// </summary>
        public static string Internet {
            get {
                return ResourceManager.GetString("Internet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jewelry.
        /// </summary>
        public static string Jewelry {
            get {
                return ResourceManager.GetString("Jewelry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kids.
        /// </summary>
        public static string Kids {
            get {
                return ResourceManager.GetString("Kids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lend.
        /// </summary>
        public static string Lend {
            get {
                return ResourceManager.GetString("Lend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Insurance.
        /// </summary>
        public static string MedicalInsurance {
            get {
                return ResourceManager.GetString("MedicalInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicines.
        /// </summary>
        public static string Medicines {
            get {
                return ResourceManager.GetString("Medicines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc..
        /// </summary>
        public static string Misc {
            get {
                return ResourceManager.GetString("Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Phone.
        /// </summary>
        public static string MobilePhone {
            get {
                return ResourceManager.GetString("MobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movies.
        /// </summary>
        public static string Movies {
            get {
                return ResourceManager.GetString("Movies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        public static string Music {
            get {
                return ResourceManager.GetString("Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parking.
        /// </summary>
        public static string Parking {
            get {
                return ResourceManager.GetString("Parking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parks.
        /// </summary>
        public static string Parks {
            get {
                return ResourceManager.GetString("Parks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal.
        /// </summary>
        public static string Personal {
            get {
                return ResourceManager.GetString("Personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pets.
        /// </summary>
        public static string Pets {
            get {
                return ResourceManager.GetString("Pets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Transport.
        /// </summary>
        public static string PublicTransport {
            get {
                return ResourceManager.GetString("PublicTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recreation.
        /// </summary>
        public static string Recreation {
            get {
                return ResourceManager.GetString("Recreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent.
        /// </summary>
        public static string Rent {
            get {
                return ResourceManager.GetString("Rent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repayment.
        /// </summary>
        public static string Repayment {
            get {
                return ResourceManager.GetString("Repayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant.
        /// </summary>
        public static string Restaurant {
            get {
                return ResourceManager.GetString("Restaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        public static string Salary {
            get {
                return ResourceManager.GetString("Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoes.
        /// </summary>
        public static string Shoes {
            get {
                return ResourceManager.GetString("Shoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport.
        /// </summary>
        public static string Sport {
            get {
                return ResourceManager.GetString("Sport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxes.
        /// </summary>
        public static string Taxes {
            get {
                return ResourceManager.GetString("Taxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxi.
        /// </summary>
        public static string Taxi {
            get {
                return ResourceManager.GetString("Taxi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Television.
        /// </summary>
        public static string Television {
            get {
                return ResourceManager.GetString("Television", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Therapy.
        /// </summary>
        public static string Therapy {
            get {
                return ResourceManager.GetString("Therapy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tolls.
        /// </summary>
        public static string Tolls {
            get {
                return ResourceManager.GetString("Tolls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toys.
        /// </summary>
        public static string Toys {
            get {
                return ResourceManager.GetString("Toys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer from.
        /// </summary>
        public static string TransferFrom {
            get {
                return ResourceManager.GetString("TransferFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer to.
        /// </summary>
        public static string TransferTo {
            get {
                return ResourceManager.GetString("TransferTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport.
        /// </summary>
        public static string Transport {
            get {
                return ResourceManager.GetString("Transport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel.
        /// </summary>
        public static string Travel {
            get {
                return ResourceManager.GetString("Travel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuition.
        /// </summary>
        public static string Tuition {
            get {
                return ResourceManager.GetString("Tuition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilities.
        /// </summary>
        public static string Utilities {
            get {
                return ResourceManager.GetString("Utilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacation.
        /// </summary>
        public static string Vacation {
            get {
                return ResourceManager.GetString("Vacation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water.
        /// </summary>
        public static string Water {
            get {
                return ResourceManager.GetString("Water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Μortgage.
        /// </summary>
        public static string Μortgage {
            get {
                return ResourceManager.GetString("Μortgage", resourceCulture);
            }
        }
    }
}
